function changeImat(plaque)
    -- 9 char max, preferer un format style XX-123-XX
    cls()
    gdisplay.rect( {30,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    gdisplay.rect( {60,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    gdisplay.rect( {90,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    cls()
    gdisplay.rect( {30,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    gdisplay.rect( {60,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    gdisplay.rect( {90,15}, 5,5, gdisplay.WHITE, gdisplay.WHITE )
    tmr.delayms(500)
    cls()
    gdisplay.write(10,15,plaque)
  end